version: "3"

services:
    web:
        build: .
        command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 4
        volumes:
            - .:/code
        ports:
            - 8000:8000
    db:
        image: postgres:11
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
