# Generated by Django 3.2.7 on 2021-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookie',
            old_name='name',
            new_name='location',
        ),
        migrations.AddField(
            model_name='cookie',
            name='average_cookies_per_sale',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cookie',
            name='hourly_sales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cookie',
            name='maximum_customers_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cookie',
            name='minimum_customers_per_hour',
            field=models.IntegerField(default=0),
        ),
    ]
